name: reviewdog
on: {push: {branches: [master]}, pull_request: {}}
jobs:
 reviewdog:
   name: reviewdog
   runs-on: ubuntu-latest
   steps:
     - {uses: actions/setup-go@v1, with: {go-version: 1.14}}
     - uses: actions/checkout@v2
     - name: Setup reviewdog
       run: |
         INSTALL_SHELL=https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh
         mkdir -p $HOME/bin && curl -sfL $INSTALL_SHELL| sh -s -- -b $HOME/bin
         echo ::add-path::$HOME/bin
         echo ::add-path::$(go env GOPATH)/bin # for Go projects
     - name: Run reviewdog
       env:
         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
           reviewdog -reporter=github-pr-check
