name: ci
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set go envs
      run: |
        echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
        echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH

    - name: Build
      run: go build

    - name: Test
      run: go test ./...

    - name: Install
      run: go install ./...
    
    - name: Self-check
      run: go-header $(git ls-files | grep -E '.*\.go$')
