baseURL = "/pomo"
languageCode = "en-us"
title = "Pomo"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Kevin Schoon"
    description = "Pomodoro Command Line Interface"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "./tomato.png"
